# Generated by Django 5.0 on 2023-12-17 20:11

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Moment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_ids", models.IntegerField()),
                ("content", models.TextField(blank=True, max_length=150, null=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="moments/")),
                (
                    "timestamp",
                    models.DateTimeField(
                        verbose_name=datetime.datetime(2023, 12, 17, 20, 11, 32, 363657, tzinfo=datetime.timezone.utc)
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Moment",
                "verbose_name_plural": "Moments",
                "ordering": ("-timestamp",),
                "get_latest_by": "timestamp",
            },
        ),
    ]
