# Generated by Django 5.0 on 2023-12-17 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moment",
            name="timestamp",
            field=models.DateTimeField(
                verbose_name=datetime.datetime(2023, 12, 17, 20, 16, 24, 467494, tzinfo=datetime.timezone.utc)
            ),
        ),
        migrations.AlterField(
            model_name="moment",
            name="user_ids",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
