name: Django CI
on:
  - push
  - pull_request

jobs:
  test:
    name: Django Tests
    runs-on: ubuntu-22.04

    env:
      ALLOWED_HOSTS: '*'
      SECRET_KEY: 'a secret to everybody'

    steps:
      - name: Get the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'requirements/requirements*.txt'

      - name: Install OS packages
        run: |
          # Graphviz support
          # python3-dev graphviz libgraphviz-dev
          sudo apt install \
          python3-dev graphviz libgraphviz-dev
      - name: Install Python packages
        run: pip install -r requirements/requirements.txt -r requirements/requirements-dev.txt

      - name: Test Cov
        run: make coverage
